FROM node:20-alpine

WORKDIR /app

# Dependências
COPY package*.json ./
RUN npm install

# Cópia do resto do projeto 
COPY . .

# Prisma
RUN npx prisma generate

# Build do Next
RUN npx next build

EXPOSE 3000

CMD ["npm", "start"]